# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mhlee/Downloads/libfreenect_custom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mhlee/Downloads/libfreenect_custom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mhlee/Downloads/libfreenect_custom/CMakeFiles /Users/mhlee/Downloads/libfreenect_custom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mhlee/Downloads/libfreenect_custom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named freenect

# Build rule for target.
freenect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect
.PHONY : freenect

# fast build rule for target.
freenect/fast:
	$(MAKE) -f src/CMakeFiles/freenect.dir/build.make src/CMakeFiles/freenect.dir/build
.PHONY : freenect/fast

#=============================================================================
# Target rules for targets named freenectstatic

# Build rule for target.
freenectstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenectstatic
.PHONY : freenectstatic

# fast build rule for target.
freenectstatic/fast:
	$(MAKE) -f src/CMakeFiles/freenectstatic.dir/build.make src/CMakeFiles/freenectstatic.dir/build
.PHONY : freenectstatic/fast

#=============================================================================
# Target rules for targets named freenect-regview_cpp

# Build rule for target.
freenect-regview_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect-regview_cpp
.PHONY : freenect-regview_cpp

# fast build rule for target.
freenect-regview_cpp/fast:
	$(MAKE) -f examples/CMakeFiles/freenect-regview_cpp.dir/build.make examples/CMakeFiles/freenect-regview_cpp.dir/build
.PHONY : freenect-regview_cpp/fast

#=============================================================================
# Target rules for targets named freenect_sync

# Build rule for target.
freenect_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect_sync
.PHONY : freenect_sync

# fast build rule for target.
freenect_sync/fast:
	$(MAKE) -f wrappers/c_sync/CMakeFiles/freenect_sync.dir/build.make wrappers/c_sync/CMakeFiles/freenect_sync.dir/build
.PHONY : freenect_sync/fast

#=============================================================================
# Target rules for targets named freenect_sync_static

# Build rule for target.
freenect_sync_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect_sync_static
.PHONY : freenect_sync_static

# fast build rule for target.
freenect_sync_static/fast:
	$(MAKE) -f wrappers/c_sync/CMakeFiles/freenect_sync_static.dir/build.make wrappers/c_sync/CMakeFiles/freenect_sync_static.dir/build
.PHONY : freenect_sync_static/fast

#=============================================================================
# Target rules for targets named freenect-cpp_pcview

# Build rule for target.
freenect-cpp_pcview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect-cpp_pcview
.PHONY : freenect-cpp_pcview

# fast build rule for target.
freenect-cpp_pcview/fast:
	$(MAKE) -f wrappers/cpp/CMakeFiles/freenect-cpp_pcview.dir/build.make wrappers/cpp/CMakeFiles/freenect-cpp_pcview.dir/build
.PHONY : freenect-cpp_pcview/fast

#=============================================================================
# Target rules for targets named freenect-cppview

# Build rule for target.
freenect-cppview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect-cppview
.PHONY : freenect-cppview

# fast build rule for target.
freenect-cppview/fast:
	$(MAKE) -f wrappers/cpp/CMakeFiles/freenect-cppview.dir/build.make wrappers/cpp/CMakeFiles/freenect-cppview.dir/build
.PHONY : freenect-cppview/fast

#=============================================================================
# Target rules for targets named freenect-cvdemo

# Build rule for target.
freenect-cvdemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect-cvdemo
.PHONY : freenect-cvdemo

# fast build rule for target.
freenect-cvdemo/fast:
	$(MAKE) -f wrappers/opencv/CMakeFiles/freenect-cvdemo.dir/build.make wrappers/opencv/CMakeFiles/freenect-cvdemo.dir/build
.PHONY : freenect-cvdemo/fast

#=============================================================================
# Target rules for targets named freenect_cv

# Build rule for target.
freenect_cv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freenect_cv
.PHONY : freenect_cv

# fast build rule for target.
freenect_cv/fast:
	$(MAKE) -f wrappers/opencv/CMakeFiles/freenect_cv.dir/build.make wrappers/opencv/CMakeFiles/freenect_cv.dir/build
.PHONY : freenect_cv/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... uninstall"
	@echo "... freenectstatic"
	@echo "... freenect"
	@echo "... freenect-regview_cpp"
	@echo "... freenect_sync_static"
	@echo "... freenect_sync"
	@echo "... freenect-cpp_pcview"
	@echo "... freenect-cppview"
	@echo "... freenect_cv"
	@echo "... freenect-cvdemo"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

